# Copyright Advanced Micro Devices, Inc.
#
# SPDX-License-Identifier: Apache-2.0

"""Shared substrate file and provenance helpers."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Iterable, List, Sequence

DEFAULT_CODE_DOC_EXTS = {
    ".c", ".cc", ".cpp", ".cxx", ".h", ".hpp", ".hxx",
    ".py", ".pyi", ".ipynb",
    ".go", ".rs", ".java", ".kt",
    ".js", ".mjs", ".cjs", ".ts", ".tsx",
    ".rb", ".php", ".cs", ".swift",
    ".md", ".rst", ".txt",
    ".yml", ".yaml", ".toml", ".json", ".ini", ".cfg",
    ".sh", ".bash", ".zsh", ".ps1",
    ".sql", ".proto",
}

DEFAULT_DATA_EXTS = {".csv", ".geojson"}
DEFAULT_EXCLUDE_DIRS = {
    ".git",
    ".hg",
    ".svn",
    "node_modules",
    "vendor",
    "third_party",
    "external",
    "build",
    "dist",
    "out",
    "target",
    "bazel-bin",
    "bazel-out",
    "buck-out",
    ".venv",
    "venv",
    "__pycache__",
}


def load_repo_id(substrate_root: Path, default_label: str = "substrate") -> str:
    """Read substrate provenance and build a stable repository id.

    Args:
        substrate_root: Substrate root path.
        default_label: Fallback source label.

    Returns:
        Repo id string in ``<label>@<revision>`` format.
    """
    provenance = substrate_root / "provenance.json"
    if not provenance.exists():
        return f"{default_label}@unknown"
    try:
        payload = json.loads(provenance.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return f"{default_label}@unknown"
    label = payload.get("source_label", default_label)
    revision = payload.get("source_git_revision", "unknown")
    return f"{label}@{revision}"


def load_file_list(substrate_root: Path, include_exts: Sequence[str] | Iterable[str]) -> List[Path]:
    """Load deterministic substrate file list.

    Prefers ``manifest.jsonl`` generated by substrate builders. Falls back to a
    recursive scan when the manifest is missing.

    Args:
        substrate_root: Substrate root directory.
        include_exts: Allowed extensions.

    Returns:
        Sorted relative file paths.
    """
    include = {ext.lower() for ext in include_exts}
    manifest = substrate_root / "manifest.jsonl"
    if manifest.exists():
        paths: List[Path] = []
        for line in manifest.read_text(encoding="utf-8").splitlines():
            if not line.strip():
                continue
            row = json.loads(line)
            rel = Path(row["path"])
            if rel.suffix.lower() in include:
                paths.append(rel)
        return sorted(paths)

    paths = []
    for path in substrate_root.rglob("*"):
        if not path.is_file():
            continue
        rel = path.relative_to(substrate_root)
        if rel.as_posix() == "manifest.jsonl":
            continue
        if rel.suffix.lower() in include:
            paths.append(rel)
    return sorted(paths)
